# -*- coding: utf-8 -*-
"""reading and writing images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqP0Qh1Fv_MNphj3bGUlaiFox526X6wg

### Download the code zip file
"""

from matplotlib import pyplot as plt
import argparse
import cv2

def plt_imshow(title, image):
	image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
	plt.imshow(image)
	plt.title(title)
	plt.grid(False)
	plt.show()

"""### Implementing our OpenCV image loading script"""

args = {
	"image": "30th_birthday.png",
}

image = cv2.imread(args["image"])
(h, w, c) = image.shape[:3]

print("width: {} pixels".format(image.shape[1]))
print("height: {}  pixels".format(image.shape[0]))
print("channels: {}".format(image.shape[2]))

plt_imshow("Image", image)

cv2.imwrite("newimage.jpg", image)